

version: '3.1'

services:
  mangaxapp:
    build: 
      context: .
      dockerfile: Dockerfile
    image: manga-docker
    container_name: mangaxapp
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      DBHOST: ${RDS_DATABASE_HOST}
      DBPORT: ${RDS_DATABASE_PORT}
      DBUSER: ${RDS_DATABASE_USER}
      DBPASSWORD: ${RDS_DATABASE_PASSWORD}
      DATABASE: ${DATABASE_NAME}
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}