

version: '3.1'

services:
  mangaxapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: manga-docker
    container_name: mangaxapp
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      DBHOST: db
      DBPORT: ${DBPORT}
      DBUSER: ${DBUSER}
      DBPASSWORD: ${DBPASSWORD}
      DATABASE: ${DATABASE}
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}

  db:
    image: postgres:15.1
    container_name: postgres-manga
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_USER: ${DBUSER}
#    volumes:
#      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432