
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'Urranrell318'
      POSTGRES_USER: 'sovering'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432