
name: DockerBuild

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions:checkout@v2

    - name: login DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: urranrell/manga-api:latest