
name: DockerBuild

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions:checkout@v4

    - name: login DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ../Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/manga-api:latest