
name: docker-deploy-lambda

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ECR_DEFAULT_TAG: latest
      AWS_DEFAULT_REGION: us-east-1

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCES_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCES_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      
      -
        name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      -
        name: Build and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: manga-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f ./Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      -
        name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name ${{ env.LAMBDA_NAME }} --image-uri "${{ env.AWS_ECR_IMAGE_URI }}:${{ env.IMAGE_TAG }}"
        env:
          LAMBDA_NAME: lessmanga
          AWS_ECR_IMAGE_URI: 990307636431.dkr.ecr.us-east-1.amazonaws.com/manga-api
          IMAGE_TAG: ${{ github.sha }}